### ISSUE TITLE
There has to be a editor toolbar for the general functionalities the tmodel editor offers.

### ISSUE THREAD

**Issue by PhilMFischer** [DLR-SC/Overtarget#27]
Add a toolbar, which has the following buttons:

- [x] Start up resolver (related to #26)
- [x] Update all versions (Related to #24)
- [x] Generate target plattform file (Related to #28)
- [x] Resolve target platform (related to #25)

- [x] The toolbar should appear somewhere here:

![grafik](https://user-images.githubusercontent.com/35496033/64008764-07f9ab80-cb17-11e9-9d75-4a0885cc2f58.png)

- [x] The commands and buttons should also appear in the context menu of the editor.
- [x] The commnads and buttons should also appear in the main menu, as soon as the editor has the context
